- name: "creates a directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "move the backend files to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm i 
    
- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    
- name: "run migrations"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations
    
- name: "execute server in pm2"
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls