- name: "move the backend files to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "stop server in pm2"
  ignore_errors: yes
  shell: |
    pm2 stop backend
    pm2 delete backend

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm i 
    
- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    
- name: "execute server in pm2"
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start